version: '3.4'

services:
  seniorcrud:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: shell
    ports:
      - "127.0.0.1:3000:3000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: mymongodatabase
    image: mongo
    ports:
      - "27018:27017"
    logging:
      driver: none
